<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Movie\Handler\MovielistHandler::class => Movie\Handler\MovielistHandlerFactory::class,
            Movies\Handle\RenderMoviesHandler::class => Movies\Handle\RenderMoviesHandlerFactory::class,
            User\Handler\RegisterHandler::class => User\Handler\RegisterHandlerFactory::class,
        ],
    ],
];
